### PR TITLE
add new script

### PR DESCRIPTION
**Pull request by SadaakiEmura**
- jenkins_tree

https://github.com/SadaakiEmura/jenkins_support_tool-1

### CODE REVIEW

**Comment by freddiefujiwara-rakuten** [comment]
@SadaakiEmura 
Thanks for giving us the PR

I have 3 points for you
1. jenkins_tree/image/
do you have the copy right of them?

2. no license is not acceptable
so please add MIT or other

3. no README is not acceptable
please add at least 
Getting started
Introduction

ref
https://github.com/rakutentech/shibuya

Thanks

**Comment by SadaakiEmura** [comment]
modify image & readme

**Comment by SadaakiEmura** [comment]
fix moji-bake
add LICENSE

**Comment by freddiefujiwara-rakuten** [comment]
@SadaakiEmura  thanks for quickly updating
FIXED:jenkins_tree/image/
do you have the copy right of them?

FIXED:no license is not acceptable
so please add MIT or other

NEED TO MODIFY:no README is not acceptable

How about copying the instructions into a README
[Instructions]

https://qiita.com/emurin/items/b81241d159e69ab5c74e
And then I think users will be able to use it right away.

**Comment by SadaakiEmura** [comment]
change README to .md

**Comment by freddiefujiwara-rakuten** [comment]
Thanks I'll merge it

**Pull request merged**
